[package]
name = "oni"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1"
anyhow = "1"
bitflags = "1"
memmap2 = "0.5"
bytemuck = { version="1", features=["derive"] }
memchr = "2"
strum = { version = "0.24", features = ["derive"] }
log = "0.4"
env_logger = "0.9"